import React from "react";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { LocomotiveScrollWrapper, NavBar } from "../components";
import { Footer } from "../sections";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Sombra | Welcome...",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <body>
        <LocomotiveScrollWrapper>
          <NavBar />
          {children}
          <Footer />
        </LocomotiveScrollWrapper>
      </body>
    </html>
  );
}
